apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-data-volume-1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/guo/software/hdfs/data/volume-1"

  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - alluxio-hdfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-data-volume-2
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/guo/software/hdfs/data/volume-2"
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - alluxio-hdfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-data-volume-3
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/guo/software/hdfs/data/volume-3"
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - alluxio-hdfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-data-volume-4
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/guo/software/hdfs/data/volume-4"
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - alluxio-hdfs