
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alluxio-journal
  labels:
    type: local
    app: alluxio
    component: alluxio-journal
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/guo/software/alluxio/journal"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alluxio-hadoop-native-lib
  labels:
    type: local
    app: alluxio
    component: alluxio-java-lib
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/guo/software/alluxio/hadoop-native-lib
